[project]
name = "padel-monitor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "python-telegram-bot>=22.2",
    "aiohttp>=3.9.1",
    "beautifulsoup4>=4.12.2",
    "requests>=2.32.4",
]
